class FontConstants {
  static const exsmall = 12.0;
  static const small = 14.0;
  static const medium = 16.0;
  static const large = 18.0;
  static const xlarge = 20.0;
  static const xxlarge = 24.0;
  static const xxxlarge = 30.0;
  static const huge = 36.0;
}

class TextConstants {
  static const homeHeading = 'Find Match';
  static const discover = 'Discover';
  static const search = 'search';
  static const filter = 'Filter';
  static const matchDeatil = 'Find your perfect match';
  static const login = 'Hey';
  static const loginDetail = 'Welcome to urgent rishta! Login to your account.';
  static const remenberPsd = 'Remenber Password';
  static const forgotpsd = 'Forgot password?';
  static const createPsd = 'Create a new password';
  static const email = 'Email';
  static const loginbyNo = 'Login using mobile number';
  static const phoneNo = 'Phone number';
  static const signin = 'Sign in';
  static const dontHaveAccount = "Don't have an account?";
  static const haveAccount = 'Already have an account?';
  static const register = 'Register now';
  static const registration = 'Registration';
  static const password = 'Password';
  static const forgotdetail =
      'Where would you like to receive a reset password link?';
  static const vsms = 'via sms';
  static const vemail = 'via email';
  static const next = 'Next';
  static const resetPsd = 'Reset Password';
  static const acceptAgree = 'Accept and Continue';
  static const notAcceptAgree = 'Do not Accept';
  static const termTitle = 'Terms and Conditions';
  static const verify = 'Verify';
  static const mailCheck = 'Verify your email';
  static const mailDetail = 'Sent a verification code to';
  static const verifyDetail = 'Please enter the code we send you';
  static const resent = 'Resend code';
  static const notReceive = "Didn't receive the code? ";
  static const acceptTerms = "I have read & accepted terms and conditions";

  static const List<String> genderList = [
    'Male',
    'Female',
  ];
  static const List<String> religionList = [
    'Ahmadiyya',
    'Bahá\'í Faith',
    'Buddhism',
    'Christianity',
    'Hinduism',
    'Irreligion',
    'Islam',
    'Jainism',
    'Judaism',
    'Kalash',
    'Sikhism',
    'Zoroastrianism',
    'other',
  ];

  static const List<String> sectList = [
    // Islam
    'Sunni',
    'Shia',
    'Sufism',
    'Ahmadiyya',
    'Ibadi',
  ];

  static const List<String> casteList = [
    'Abbasi',
    'Ansari',
    'Arain',
    'Awan',
    'Baloch',
    'Bhatti',
    'Bhutto',
    'Bugti',
    'Butt',
    'Chandio',
    'Chaudhry',
    'Dogar',
    'Gopang',
    'Gujjar',
    'Ismaili',
    'Jalwana',
    'Janjua',
    'Jat',
    'Jatoi',
    'Jutt',
    'Kashmiri',
    'Khatri',
    'Khanzada',
    'Khattar',
    'Khokhar',
    'Lashari',
    'Langah',
    'Leghari',
    'Lohar',
    'Malik',
    'Magsi',
    'Marri',
    'Mazari',
    'Mehar',
    'Memon',
    'Mengal',
    'Mughal',
    'Muhajir',
    'Pathan',
    'Punjabi',
    'Pashtun',
    'Qureshi',
    'Rajput',
    'Raisani',
    'Rind',
    'Saini',
    'Saraiki',
    'Sayed',
    'Sheikh',
    'Sindhi',
    'Syed',
    'Talpur',
    'Tareen',
    'Zardari',
    'Hazara',
    'other',
  ];

  static const List<String> maritalStatusList = [
    'Single',
    'Married',
    'Divorced',
    'Widowed',
    'Widower',
    'Separated',
    'Waiting for Divorce',
  ];
  static const List<String> jobAndBusinessList = [
    "Job",
    "Bussines",
  ];
  static const List<String> noList = [
    'None',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10+',
  ];
  static const List<String> weightList = [
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
    '41',
    '42',
    '43',
    '44',
    '45',
    '46',
    '47',
    '48',
    '49',
    '50',
    '51',
    '52',
    '53',
    '54',
    '55',
    '56',
    '57',
    '58',
    '59',
    '60',
    '61',
    '62',
    '63',
    '64',
    '65',
    '66',
    '67',
    '68',
    '69',
    '70',
    '71',
    '72',
    '73',
    '74',
    '75',
    '76',
    '77',
    '78',
    '79',
    '80',
    '81',
    '82',
    '83',
    '84',
    '85',
    '86',
    '87',
    '88',
    '89',
    '90',
    '91',
    '92',
    '93',
    '94',
    '95',
    '96',
    '97',
    '98',
    '99',
    '100+',
  ];

  static const List<String> homeStatusList = [
    'Own',
    'Rent',
  ];
  static const List<String> qualificationList = [
    'None',
    'High School',
    'Diploma/GED',
    'ADP',
    'BA',
    'BBA',
    'B.Com',
    'BDS',
    'B.Ed',
    'BS',
    'LLB',
    'MBBS',
    'CA',
    'Ed.D',
    'LLM',
    'MA',
    'M.Com',
    'M.Ed',
    'MBA',
    'MD',
    'M.Phil',
    'MS/M.Sc',
    'Ph.D',
    'Other',
  ];

  static const List<String> heightList = [
    'less than 4 ft',
    '4\'0"',
    '4\'1"',
    '4\'2"',
    '4\'3"',
    '4\'4"',
    '4\'5"',
    '4\'6"',
    '4\'7"',
    '4\'8"',
    '4\'9"',
    '4\'10"',
    '4\'11"',
    '5\'0"',
    '5\'1"',
    '5\'2"',
    '5\'3"',
    '5\'4"',
    '5\'5"',
    '5\'6"',
    '5\'7"',
    '5\'8"',
    '5\'9"',
    '5\'10"',
    '5\'11"',
    '6\'0"',
    '6\'1"',
    '6\'2"',
    '6\'3"',
    '6\'4"',
    '6\'5"',
    '6\'6"',
    '6\'7"',
    '6\'8"',
    '6\'9"',
    '6\'9"+',
  ];
  static const List<String> ageList = [
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
    '41',
    '42',
    '43',
    '44',
    '45',
    '46',
    '47',
    '48',
    '49',
    '50',
  ];

  static const List<String> yesNoList = [
    'Yes',
    'No',
  ];
  static const List<String> provinceList = [
    'Balochistan',
    'Khyber Pakhtunkhwa',
    'Punjab',
    'Sindh',
    'Gilgit-Baltistan',
    'FATA ',
  ];
  static const List<String> pakistanCitiesList = [
    'Abbottabad',
    'Attock',
    'Badin',
    'Bagh',
    'Bahawalnagar',
    'Bahawalpur',
    'Bannu',
    'Barkhan',
    'Batkhela',
    'Bhakkar',
    'Bhimber',
    'Charsadda',
    'Chakwal',
    'Chaman',
    'Chilas',
    'Chiniot',
    'Chitral',
    'Dadu',
    'Daska',
    'Dera Allahyar',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Faisalabad',
    'Gahkuch',
    'Ghotki',
    'Gilgit',
    'Gujranwala',
    'Gujrat',
    'Gwadar',
    'Gupis',
    'Hafizabad',
    'Hangu',
    'Haripur',
    'Harnai',
    'Hassan Abdal',
    'Hattian Bala',
    'Haveli',
    'Hub',
    'Hunza',
    'Hyderabad',
    'Islamabad',
    'Ishkoman',
    'Jacobabad',
    'Jaffarabad',
    'Jamshed Town',
    'Jhang',
    'Jhelum',
    'Kalat',
    'Kamalia',
    'Kamoke',
    'Kambar Shahdadkot',
    'Karachi',
    'Karak',
    'Kasur',
    'Kech',
    'Khairpur',
    'Khanewal',
    'Kharan',
    'Khaplu',
    'Khushab',
    'Khyber Pakhtunkhwa',
    'Killa Abdullah',
    'Kohat',
    'Kohistan',
    'Kotli',
    'Korangi',
    'Lahore',
    'Lakki Marwat',
    'Landi',
    'Larkana',
    'Layyah',
    'Lodhran',
    'Lower Dir',
    'Malakand',
    'Malir',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Mastung',
    'Matiari',
    'Mianwali',
    'Mirpur',
    'Mirpur Khas',
    'Mithi',
    'Mingora',
    'Multan',
    'Muzaffarabad',
    'Muzaffargarh',
    'Nagar',
    'Nankana Sahib',
    'Narowal',
    'Naushahro Feroze',
    'Nawabshah',
    'Neelam',
    'North Nazimabad',
    'Nowshera',
    'Nushki',
    'Okara',
    'Pakpattan',
    'Panjgur',
    'Peshawar',
    'Pishin',
    'Quetta',
    'Qilla Saifullah',
    'Rahim Yar Khan',
    'Rajanpur',
    'Rawalakot',
    'Rawalpindi',
    'Sadiqabad',
    'Sahiwal',
    'Sanghar',
    'Sargodha',
    'Shahdadkot',
    'Sheikhupura',
    'Shikarpur',
    'Shigar',
    'Sialkot',
    'Skardu',
    'Sujawal',
    'Sukkur',
    'Swabi',
    'Swat',
    'Tank',
    'Tando Adam',
    'Tando Allahyar',
    'Tharparkar',
    'Thatta',
    'Toba Tek Singh',
    'Turbat',
    'Umerkot',
    'Upper Dir',
    'Vehari',
    'Wah Cantonment',
    'Washuk',
    'Yasin',
    'Zhob',
    'Ziarat',
    'other',
  ];
  static const List<String> skinColorList = [
    'Very Light',
    'Light',
    'Fair',
    'Medium',
    'Olive',
    'Tan',
    'Dark',
    'Very Dark',
  ];
  static const termsHeading =
      'Please read the following terms and conditions carefully. By accepting, you agree to abide by them. Only proceed if you accept these terms and conditions.';
  static const paymentDetails =
      "Discover true love with Rishta Registry App! Unlock all features for a lifetime with just Rs. 2,000 – find your soulmate effortlessly.";
  static const termsAggrement =
      '1. Users must provide accurate information on Rishta App profiles.\n2. Profile information may be verified for authenticity.\n3. Rishta App reserves the right to cross-verify profiles.\n4. The company will keep your personal data private.\n5. Legal action may be taken against fraudulent activity.\n6. Users must adhere to respectful conductguidelines.\n7. Inappropriate content will be removed from the platform.\n8. Privacy Policy governs user data handling.\n9. Terms and conditions are subject to change.\n10.Disputes will be resolved according to local laws.';
  static const String termHeadingUrdu =
      'برائے کرم مندرجہ ذیل شرائط اور شرائط کو دھیان سے پڑھیں۔ انہیں قبول کرنے کے بعد آپ ان پر عمل کرنے کے لئے رضامند ہیں۔ صرف اس صورت میں آگے بڑھیں جب آپ ان شرائط اور شرائط کو قبول کریں۔';

  static const String termAgreementUrdu =
      '۔ صارفین کو رشتہ ایپ پروفائلز پر درست معلومات فراہم کرنی چاہئیں۔\n۔ پروفائل کی معلومات کی سچائی کی تصدیق کی جا سکتی ہے۔\n۔ رشتہ ایپ کو پروفائلوں کی تصدیق کرنے کا حق محفوظ ہے۔\n۔ کمپنی آپ کی شخصی معلومات کو نجی رکھے گی۔\n۔ فریبی سرگرمی کے خلاف قانونی کارروائی کی جا سکتی ہے۔\n۔ صارفین کو احترام اندازی کے قواعد پر عمل کرنا ہوگا۔\n۔ غیر معمولی مواد کو پلیٹ فارم سے ہٹا دیا جائے گا۔\n۔ رازداری پالیسی صارفین کی معلومات کا منصوبہ بندی کرتی ہے۔\n۔ شرائط اور شرائط میں تبدیلی کے قابل ہیں۔\n۔ تنازعات مقامی قوانین کے مطابق حل کیے جائیں گے۔';
}
